spring:
  datasource:
    url:
    username:
    password:
  redis:
    host:
    port:
    password:
    database:
aliyun:
  oss:
    endpoint:
    access-key:
    access-secret:
    bucket-name:
    prefix: